cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

tap "1password/tap"
tap "github/gh"
tap "hashicorp/tap"

brew "antigen"
brew "gh"
brew "git"
brew "mas"
brew "node"
brew "nvm"
brew "shellcheck"
brew "starship"
brew "vim"
brew "wget"
brew "zsh"

# gnu stuff
brew "coreutils"
brew "findutils"
brew "gnu-tar"
brew "gnu-sed"
brew "gawk"
brew "gnutls"
brew "gnu-indent"
brew "gnu-getopt"

cask "1password"
cask "1password/tap/1password-cli"
cask "alfred"
cask "docker"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "github"
cask "imageoptim"
cask "iterm2"
cask "jetbrains-toolbox"
cask "microsoft-edge"
cask "microsoft-office"
cask "microsoft-teams"
cask "raycast"
cask "setapp"
cask "sublime-text"
cask "tinkerwell"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"
