#!/bin/sh
alias npis='npm install --save'
alias npisd='npm install --save-dev'
alias npig='npm install -g'
alias npit='npm init'
alias npi='npm install'
alias yip='yarn install && yarn prod'
alias nip='npm install && npm run prod'
alias nib='npm install && npm run build'
alias nid='npm install && npm run dev'
