#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias cp="cp -iv"
#             │└─ list copied files
#             └─ prompt before overwriting an existing file

alias mkdir="mkdir -pv"
#                   │└─ list created directories
#                   └─ create intermediate directories

alias mv="mv -iv"
#             │└─ list moved files
#             └─ prompt before overwriting an existing file

alias rm="rm -rf --"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias d="cd ~/Desktop"
alias e="vim --"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias code="cd ~/Code"
alias sites="cd ~/Sites"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias y="yarn"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Laravel Artisans
alias art='php artisan'
alias am='php artisan migrate'
alias amr='php artisan migrate:rollback'
alias amf='php artisan migrate:fresh'
alias adbs='php artisan db:seed'
alias amfdbs='php artisan migrate:rollback && php artisan migrate && php artisan db:seed'
alias artclear='art clear && art config:clear && art cache:clear && art view:clear && art route:clear && composer dump-autoload'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific configs.

. "$OS/bash_aliases"
